"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createMemberGroupController = void 0;
var MembersGroupRepository_1 = require("../../repositories/implementations/MembersGroupRepository");
var CreateMemberGroupController_1 = require("./CreateMemberGroupController");
var CreateMemberGroupUseCase_1 = require("./CreateMemberGroupUseCase");
var memberGroupRepository = MembersGroupRepository_1.MembersGroupRepository.getInstance();
var createMemberGroupUseCase = new CreateMemberGroupUseCase_1.CreateMemberGroupUseCase(memberGroupRepository);
var createMemberGroupController = new CreateMemberGroupController_1.CreateMemberGroupController(createMemberGroupUseCase);
exports.createMemberGroupController = createMemberGroupController;
