"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createNewsletterController = void 0;
var NewsletterRepository_1 = require("../../repositories/implementation/NewsletterRepository");
var CreateNewsletterController_1 = require("./CreateNewsletterController");
var CreateNewsletterUsecase_1 = require("./CreateNewsletterUsecase");
var newsletterRepository = NewsletterRepository_1.NewsletterRepository.getInstance();
var createNewsletteruseCase = new CreateNewsletterUsecase_1.CreateNewsletteruseCase(newsletterRepository);
var createNewsletterController = new CreateNewsletterController_1.CreateNewsletterController(createNewsletteruseCase);
exports.createNewsletterController = createNewsletterController;
