"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createCommentsController = void 0;
var CommentsRepository_1 = require("../../repositories/implementations/CommentsRepository");
var CreateCommentsController_1 = require("./CreateCommentsController");
var CreateCommentsUseCase_1 = require("./CreateCommentsUseCase");
var commentRepository = CommentsRepository_1.CommentsRepository.getInstance();
var createCommentsGroupUseCase = new CreateCommentsUseCase_1.CreateCommentsUseCase(commentRepository);
var createCommentsController = new CreateCommentsController_1.CreateCommentsController(createCommentsGroupUseCase);
exports.createCommentsController = createCommentsController;
