"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createFriendsController = void 0;
var FriendsRepository_1 = require("../../repositories/implementations/FriendsRepository");
var CreateFriendsController_1 = require("./CreateFriendsController");
var CreateFriendstUseCase_1 = require("./CreateFriendstUseCase");
var friendsRepository = FriendsRepository_1.FriendsRepository.getInstance();
var createFriendsUseCase = new CreateFriendstUseCase_1.CreateFriendsUseCase(friendsRepository);
var createFriendsController = new CreateFriendsController_1.CreateFriendsController(createFriendsUseCase);
exports.createFriendsController = createFriendsController;
