"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createAccountController = void 0;
var AccountsRepository_1 = require("../../repositories/implementations/AccountsRepository");
var CreateAccountController_1 = require("./CreateAccountController");
var CreateAccountUseCase_1 = require("./CreateAccountUseCase");
var accountsRepository = AccountsRepository_1.AccountsRepository.getInstance();
var createAccountUseCase = new CreateAccountUseCase_1.CreateAccountUseCase(accountsRepository);
var createAccountController = new CreateAccountController_1.CreateAccountController(createAccountUseCase);
exports.createAccountController = createAccountController;
