"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateInformationsController = void 0;
var InformationsRepository_1 = require("../../repositories/implementations/InformationsRepository");
var UpdateInformationsController_1 = require("./UpdateInformationsController");
var UpdateInformationsUseCase_1 = require("./UpdateInformationsUseCase");
var informationsRepository = InformationsRepository_1.InformationsRepository.getInstance();
var updateInformationsUseCase = new UpdateInformationsUseCase_1.UpdateInformationsUseCase(informationsRepository);
var updateInformationsController = new UpdateInformationsController_1.UpdateInformationsController(updateInformationsUseCase);
exports.updateInformationsController = updateInformationsController;
