"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createLikePostController = void 0;
var LikePostRepository_1 = require("../../repositories/implementations/LikePostRepository");
var CreateLikePostController_1 = require("./CreateLikePostController");
var CreateLikePostUseCase_1 = require("./CreateLikePostUseCase");
var likePostRepository = LikePostRepository_1.LikePostRepository.getInstance();
var createLikePostUseCase = new CreateLikePostUseCase_1.CreateLikePostUseCase(likePostRepository);
var createLikePostController = new CreateLikePostController_1.CreateLikePostController(createLikePostUseCase);
exports.createLikePostController = createLikePostController;
