"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createFollowersController = void 0;
var FollowersRepository_1 = require("../../repositories/implementations/FollowersRepository");
var CreateFollowersController_1 = require("./CreateFollowersController");
var CreateFollowerstUseCase_1 = require("./CreateFollowerstUseCase");
var followersRepository = FollowersRepository_1.FollowersRepository.getInstance();
var createFollowersUseCase = new CreateFollowerstUseCase_1.CreateFollowersUseCase(followersRepository);
var createFollowersController = new CreateFollowersController_1.CreateFollowersController(createFollowersUseCase);
exports.createFollowersController = createFollowersController;
