"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createGroupController = void 0;
var GroupsRepository_1 = require("../../repositories/implementations/GroupsRepository");
var CreateGroupController_1 = require("./CreateGroupController");
var CreateGroupUseCase_1 = require("./CreateGroupUseCase");
var groupsRepository = GroupsRepository_1.GroupsRepository.getInstance();
var createGroupUseCase = new CreateGroupUseCase_1.CreateGroupUseCase(groupsRepository);
var createGroupController = new CreateGroupController_1.CreateGroupController(createGroupUseCase);
exports.createGroupController = createGroupController;
