"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authenticateAccountController = void 0;
var AccountsRepository_1 = require("../../repositories/implementations/AccountsRepository");
var AuthenticateAccountController_1 = require("./AuthenticateAccountController");
var AuthenticateAccountUseCase_1 = require("./AuthenticateAccountUseCase");
var accountsRepository = AccountsRepository_1.AccountsRepository.getInstance();
var authenticateAccountUseCase = new AuthenticateAccountUseCase_1.AuthenticateAccountUseCase(accountsRepository);
var authenticateAccountController = new AuthenticateAccountController_1.AuthenticateAccountController(authenticateAccountUseCase);
exports.authenticateAccountController = authenticateAccountController;
